development:
  adapter: postgresql
  database: petitvoiture_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: petitvoiture_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: petitvoiture_production
  pool: 5
  timeout: 5000
